INSERT INTO [users].[Permissions] ([Code]) VALUES
('carts:add'),
('carts:read'),
('carts:remove'),
('categories:read'),
('categories:update'),
('event-statistics:read'),
('events:read'),
('events:search'),
('events:update'),
('orders:create'),
('orders:read'),
('ticket-types:read'),
('ticket-types:update'),
('tickets:check-in'),
('tickets:read'),
('users:read'),
('users:update');

INSERT INTO [users].[Roles] ([Name]) VALUES
('Administrator'),
('Member');

INSERT INTO [users].[RolePermissions] ([PermissionCode], [RoleName]) VALUES
('carts:add', 'Administrator'),
('carts:add', 'Member'),
('carts:read', 'Administrator'),
('carts:read', 'Member'),
('carts:remove', 'Administrator'),
('carts:remove', 'Member'),
('categories:read', 'Administrator'),
('categories:update', 'Administrator'),
('event-statistics:read', 'Administrator'),
('events:read', 'Administrator'),
('events:search', 'Administrator'),
('events:search', 'Member'),
('events:update', 'Administrator'),
('orders:create', 'Administrator'),
('orders:create', 'Member'),
('orders:read', 'Administrator'),
('orders:read', 'Member'),
('ticket-types:read', 'Administrator'),
('ticket-types:read', 'Member'),
('ticket-types:update', 'Administrator'),
('tickets:check-in', 'Administrator'),
('tickets:check-in', 'Member'),
('tickets:read', 'Administrator'),
('tickets:read', 'Member'),
('users:read', 'Administrator'),
('users:read', 'Member'),
('users:update', 'Administrator'),
('users:update', 'Member');